### PR TITLE
Fix #100 - improve multilingual support

### LINKED ISSUE #100: Can´t create alarm
```
~~~~oft_skill:on_error:835 | Bei der Verarbeitung der Anfrage ist ein Fehler im Skill Alarm Skill aufgetreten.Traceback (most recent call last):                                                                              
File "/home/pi/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper               
handler(message)                                                                                            
File "/opt/mycroft/skills/mycroft-alarm.mycroftai/__init__.py", line 394, in handle_set_alarm                   
today = today[0]                                                                                          
TypeError: 'NoneType' object is not subscriptable         
```

### PR DESCRIPTION
**Pull request by krisgesling**
When extracting datetime of pre-defined "today" string, set this to be in English. This ensures the Skill works across languages, even if extract_datetime has not been localized.

Whilst investigating this I also noticed some dialog comparison checks that were not called using `self.translate` hence would be very unlikely to return true in other languages.

### CODE REVIEW

**Comment by christophfroeschl** [comment]
Any reason why this is not getting merged/approved?

**Comment by krisgesling** [comment]
Hey Christoph, looks like I forgot to assign it to someone to review.

Have you confirmed that the change fixes the issue? If so we can merge it in :)

**Comment by christophfroeschl** [comment]
@krisgesling, just tried the bugfix branch and it works

**Comment by krisgesling** [comment]
Excellent, thanks for helping us with the review :smile:

**Pull request merged**
