### PR TITLE
Improved german translation

### PR DESCRIPTION
**Pull request by gumulka**
I fixed some small errors and tried to improve the translations as best as a could to reflect german interaction with the alarm skill

### CODE REVIEW

**Comment by forslund** [comment]
Hi Can you also register the changes using https://translate.mycroft.ai otherwise it'll be overwritten the next time we pull in changes from there.

**Comment by gumulka** [comment]
How can i register new additional translations with translate?

see delete or delete-all intent

**Comment by forslund** [comment]
At the moment that is still a bit tricky. I'm hoping that we can switch to a file based system instead of a line based one.

To do this you need to use a single line and use the `|` to separate:
`((löschen|entfernen|abbrechen|deaktivieren) aller (meiner|) (Alarme|Wecker)|(lösche|entferne|deaktiviere) alle (meine|) (Alarme|Wecker)|Breche alle (Alarme|Wecker) ab)`

**Comment by gumulka** [comment]
I hope so too

**Comment by KathyReid** [comment]
I am deliberately leaving this open until we can change the format of the `po` files on Mycroft Translate

**Comment by krisgesling** [comment]
Hi all, 

I know these have been intentionally left open until a change could be made to the Pootle translation process. However given we are years in the future and still haven't got that in place, I'm going to close these and consolidate them under a dedicated issue:
https://github.com/MycroftAI/translate/issues/2

It is something we are still talking about, and support for more languages is one of the organisations priorities. So I don't want this to be taken as dismissing the issue. I just think the above issue will be a better place for them and I very much doubt that the Skill is still in a state where the translations here would make sense.

Thanks

**Pull request closed without merging**
